sudo: false
jdk: oraclejdk8
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_01f77e140031_key -iv $encrypted_01f77e140031_iv -in gradle.properties.enc -out gradle.properties -d || true
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew jacocoTestReport coveralls"
